import type { MetadataRoute } from "next";

const baseUrl = "https://www.allied247-restoration.com";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: [
        `${baseUrl}/about`,
        `${baseUrl}/contact-us`,
        `${baseUrl}/serving-areas`,
        `${baseUrl}/service`,
        `${baseUrl}/blog`,
        `${baseUrl}/service/damage-restoration`,
        `${baseUrl}/service/fire-restoration`,
        `${baseUrl}/service/mold-remediation`,
        `${baseUrl}/service/multi-surface-cleaning`,
        `${baseUrl}/service/radon-mitigation`,
        `${baseUrl}/service/reconstruction`,
        `${baseUrl}/service/water-restoration`,
        `${baseUrl}/service/damage-restoration/service-areas/bigfork-mt`,
        `${baseUrl}/service/damage-restoration/service-areas/columbia-falls-mt`,
        `${baseUrl}/service/damage-restoration/service-areas/kalispell-mt`,
        `${baseUrl}/service/damage-restoration/service-areas/lakeside-mt`,
        `${baseUrl}/service/damage-restoration/service-areas/whitefish-mt`,
        `${baseUrl}/service/fire-restoration/service-areas/bigfork-mt`,
        `${baseUrl}/service/fire-restoration/service-areas/columbia-falls-mt`,
        `${baseUrl}/service/fire-restoration/service-areas/kalispell-mt`,
        `${baseUrl}/service/fire-restoration/service-areas/lakeside-mt`,
        `${baseUrl}/service/fire-restoration/service-areas/whitefish-mt`,
        `${baseUrl}/service/mold-remediation/service-areas/bigfork-mt`,
        `${baseUrl}/service/mold-remediation/service-areas/columbia-falls-mt`,
        `${baseUrl}/service/mold-remediation/service-areas/kalispell-mt`,
        `${baseUrl}/service/mold-remediation/service-areas/lakeside-mt`,
        `${baseUrl}/service/mold-remediation/service-areas/whitefish-mt`,
        `${baseUrl}/service/multi-surface-cleaning/service-areas/bigfork-mt`,
        `${baseUrl}/service/multi-surface-cleaning/service-areas/columbia-falls-mt`,
        `${baseUrl}/service/multi-surface-cleaning/service-areas/Kalispell-mt`,
        `${baseUrl}/service/multi-surface-cleaning/service-areas/lakeside-mt`,
        `${baseUrl}/service/multi-surface-cleaning/service-areas/whitefish-mt`,
        `${baseUrl}/service/radon-mitigation/service-areas/bigfork-mt`,
        `${baseUrl}/service/radon-mitigation/service-areas/columbia-falls-mt`,
        `${baseUrl}/service/radon-mitigation/service-areas/kalispell-mt`,
        `${baseUrl}/service/radon-mitigation/service-areas/lakeside-mt`,
        `${baseUrl}/service/radon-mitigation/service-areas/whitefish-mt`,
        `${baseUrl}/service/reconstruction/service-areas/bigfork-mt`,
        `${baseUrl}/service/reconstruction/service-areas/columbia-falls-mt`,
        `${baseUrl}/service/reconstruction/service-areas/kalispell-mt`,
        `${baseUrl}/service/reconstruction/service-areas/lakeside-mt`,
        `${baseUrl}/service/reconstruction/service-areas/whitefish-mt`,
        `${baseUrl}/service/water-restoration/service-areas/bigfork-mt`,
        `${baseUrl}/service/water-restoration/service-areas/columbia-falls-mt`,
        `${baseUrl}/service/water-restoration/service-areas/kalispell-mt`,
        `${baseUrl}/service/water-restoration/service-areas/lakeside-mt`,
        `${baseUrl}/service/water-restoration/service-areas/whitefish-mt`,
        `${baseUrl}/service/radon-mitigation/service-areas`,
      ],
      disallow: ["/api/", "/_next/", "/admin/", "/private/"],
    },
    sitemap: `${baseUrl}/sitemap.xml`,
  };
}
